import Foundation

/// Complete ISO 4217 currency codes.
public enum Currency: String, Codable, CaseIterable, Identifiable, Sendable {

    // MARK: - Frequently Used Currencies

    case chf = "CHF"
    case eur = "EUR"
    case usd = "USD"
    case gbp = "GBP"
    case jpy = "JPY"

    // MARK: - Africa

    case dzd = "DZD"
    case aoa = "AOA"
    case xof = "XOF"
    case bif = "BIF"
    case cve = "CVE"
    case xaf = "XAF"
    case kmf = "KMF"
    case cdf = "CDF"
    case djf = "DJF"
    case egp = "EGP"
    case ern = "ERN"
    case szl = "SZL"
    case etb = "ETB"
    case gmd = "GMD"
    case ghs = "GHS"
    case gnf = "GNF"
    case kes = "KES"
    case lsl = "LSL"
    case lrd = "LRD"
    case lyd = "LYD"
    case mga = "MGA"
    case mwk = "MWK"
    case mru = "MRU"
    case mur = "MUR"
    case mad = "MAD"
    case mzn = "MZN"
    case nad = "NAD"
    case ngn = "NGN"
    case rwf = "RWF"
    case stn = "STN"
    case scr = "SCR"
    case sle = "SLE"
    case sos = "SOS"
    case zar = "ZAR"
    case ssp = "SSP"
    case sdg = "SDG"
    case tzs = "TZS"
    case tnd = "TND"
    case ugx = "UGX"
    case zmw = "ZMW"
    case zwl = "ZWL"

    // MARK: - Americas

    case ars = "ARS"
    case bsd = "BSD"
    case bbd = "BBD"
    case bzd = "BZD"
    case bob = "BOB"
    case brl = "BRL"
    case cad = "CAD"
    case clp = "CLP"
    case cop = "COP"
    case crc = "CRC"
    case cuc = "CUC"
    case cup = "CUP"
    case dop = "DOP"
    case xcd = "XCD"
    case fkp = "FKP"
    case gtq = "GTQ"
    case gyd = "GYD"
    case htg = "HTG"
    case hnl = "HNL"
    case jmd = "JMD"
    case mxn = "MXN"
    case nio = "NIO"
    case pab = "PAB"
    case pyg = "PYG"
    case pen = "PEN"
    case srd = "SRD"
    case ttd = "TTD"
    case uyu = "UYU"
    case ves = "VES"

    // MARK: - Asia

    case afn = "AFN"
    case amd = "AMD"
    case azn = "AZN"
    case bhd = "BHD"
    case bdt = "BDT"
    case bnd = "BND"
    case khr = "KHR"
    case cny = "CNY"
    case gel = "GEL"
    case hkd = "HKD"
    case inr = "INR"
    case idr = "IDR"
    case irr = "IRR"
    case iqd = "IQD"
    case ils = "ILS"
    case jod = "JOD"
    case kzt = "KZT"
    case kwd = "KWD"
    case kgs = "KGS"
    case lak = "LAK"
    case lbp = "LBP"
    case mop = "MOP"
    case myr = "MYR"
    case mvr = "MVR"
    case mnt = "MNT"
    case mmk = "MMK"
    case npr = "NPR"
    case kpw = "KPW"
    case omr = "OMR"
    case pkr = "PKR"
    case php = "PHP"
    case qar = "QAR"
    case sar = "SAR"
    case sgd = "SGD"
    case krw = "KRW"
    case lkr = "LKR"
    case syp = "SYP"
    case twd = "TWD"
    case tjs = "TJS"
    case thb = "THB"
    case tmt = "TMT"
    case aed = "AED"
    case uzs = "UZS"
    case vnd = "VND"
    case yer = "YER"

    // MARK: - Europe (excluding CHF, EUR, GBP)

    case all = "ALL"
    case byn = "BYN"
    case bam = "BAM"
    case bgn = "BGN"
    case hrk = "HRK"
    case czk = "CZK"
    case dkk = "DKK"
    case huf = "HUF"
    case isk = "ISK"
    case mdl = "MDL"
    case mkd = "MKD"
    case nok = "NOK"
    case pln = "PLN"
    case ron = "RON"
    case rub = "RUB"
    case rsd = "RSD"
    case sek = "SEK"
    case `try` = "TRY"
    case uah = "UAH"

    // MARK: - Oceania

    case aud = "AUD"
    case fjd = "FJD"
    case nzd = "NZD"
    case pgk = "PGK"
    case wst = "WST"
    case sbd = "SBD"
    case top = "TOP"
    case vuv = "VUV"
    case xpf = "XPF"

    // MARK: - Identifiable

    public var id: String { rawValue }

    // MARK: - Common Currencies (for pickers)

    /// Frequently used currencies, shown first in pickers.
    public static let common: [Currency] = [.usd, .eur, .gbp, .chf, .jpy, .cad, .aud, .sek, .nok, .dkk, .pln, .czk, .huf, .cny]

    // MARK: - Decimal Places

    /// Number of decimal places per ISO 4217.
    public var decimalPlaces: Int {
        switch self {
        case .bhd, .iqd, .jod, .kwd, .lyd, .omr, .tnd:
            return 3
        case .bif, .clp, .djf, .gnf, .isk, .jpy, .kmf, .kpw, .krw, .pyg, .rwf, .ugx, .vuv, .xof, .xaf, .xpf:
            return 0
        case .mru, .mga:
            return 1
        default:
            return 2
        }
    }

    // MARK: - Currency Symbol

    /// Display symbol for the currency.
    public var symbol: String {
        switch self {
        case .chf: return "Fr."
        case .eur: return "\u{20AC}"
        case .usd, .cad, .aud, .nzd, .hkd, .sgd, .mxn, .ars, .clp, .cop, .bsd, .bbd, .bzd, .jmd, .ttd, .gyd, .srd, .xcd: return "$"
        case .gbp, .egp, .lbp, .syp, .fkp: return "\u{00A3}"
        case .jpy, .cny: return "\u{00A5}"
        case .krw, .kpw: return "\u{20A9}"
        case .inr, .npr, .lkr, .mur, .pkr, .scr: return "\u{20B9}"
        case .thb: return "\u{0E3F}"
        case .ils: return "\u{20AA}"
        case .try: return "\u{20BA}"
        case .pln: return "z\u{0142}"
        case .php: return "\u{20B1}"
        case .rub: return "\u{20BD}"
        case .uah: return "\u{20B4}"
        case .sek, .nok, .dkk, .isk, .czk: return "kr"
        case .huf: return "Ft"
        case .ron: return "lei"
        case .bgn: return "лв"
        case .zar, .nad: return "R"
        case .brl: return "R$"
        case .twd: return "NT$"
        case .vnd: return "\u{20AB}"
        case .myr: return "RM"
        case .idr: return "Rp"
        case .sar, .qar, .omr, .bhd, .kwd, .aed, .yer, .irr, .iqd, .jod: return "﷼"
        case .kzt: return "\u{20B8}"
        case .gel: return "\u{20BE}"
        case .amd: return "\u{058F}"
        case .mnt: return "\u{20AE}"
        case .khr: return "\u{17DB}"
        case .lak, .mmk: return "K"
        case .ngn: return "\u{20A6}"
        case .ghs: return "GH\u{20B5}"
        case .kes, .tzs, .ugx, .sos, .rwf: return "Sh"
        default: return rawValue
        }
    }

    // MARK: - Currency Name

    /// Display name of the currency.
    public var name: String {
        switch self {
        case .chf: return "Swiss Franc"
        case .eur: return "Euro"
        case .usd: return "US Dollar"
        case .gbp: return "British Pound"
        case .jpy: return "Japanese Yen"
        case .cad: return "Canadian Dollar"
        case .aud: return "Australian Dollar"
        case .nzd: return "New Zealand Dollar"
        case .sek: return "Swedish Krona"
        case .nok: return "Norwegian Krone"
        case .dkk: return "Danish Krone"
        case .pln: return "Polish Zloty"
        case .czk: return "Czech Koruna"
        case .huf: return "Hungarian Forint"
        case .ron: return "Romanian Leu"
        case .bgn: return "Bulgarian Lev"
        case .hrk: return "Croatian Kuna"
        case .rsd: return "Serbian Dinar"
        case .bam: return "Convertible Mark"
        case .mkd: return "Macedonian Denar"
        case .all: return "Albanian Lek"
        case .mdl: return "Moldovan Leu"
        case .byn: return "Belarusian Ruble"
        case .rub: return "Russian Ruble"
        case .uah: return "Ukrainian Hryvnia"
        case .`try`: return "Turkish Lira"
        case .isk: return "Icelandic Krona"
        case .cny: return "Chinese Yuan"
        case .hkd: return "Hong Kong Dollar"
        case .twd: return "New Taiwan Dollar"
        case .krw: return "South Korean Won"
        case .kpw: return "North Korean Won"
        case .sgd: return "Singapore Dollar"
        case .myr: return "Malaysian Ringgit"
        case .thb: return "Thai Baht"
        case .idr: return "Indonesian Rupiah"
        case .php: return "Philippine Peso"
        case .vnd: return "Vietnamese Dong"
        case .inr: return "Indian Rupee"
        case .pkr: return "Pakistani Rupee"
        case .bdt: return "Bangladeshi Taka"
        case .lkr: return "Sri Lankan Rupee"
        case .npr: return "Nepalese Rupee"
        case .mmk: return "Myanmar Kyat"
        case .khr: return "Cambodian Riel"
        case .lak: return "Lao Kip"
        case .mnt: return "Mongolian Tugrik"
        case .kzt: return "Kazakh Tenge"
        case .uzs: return "Uzbek Som"
        case .kgs: return "Kyrgyz Som"
        case .tjs: return "Tajik Somoni"
        case .tmt: return "Turkmen Manat"
        case .azn: return "Azerbaijani Manat"
        case .gel: return "Georgian Lari"
        case .amd: return "Armenian Dram"
        case .afn: return "Afghan Afghani"
        case .irr: return "Iranian Rial"
        case .iqd: return "Iraqi Dinar"
        case .ils: return "Israeli Shekel"
        case .jod: return "Jordanian Dinar"
        case .kwd: return "Kuwaiti Dinar"
        case .lbp: return "Lebanese Pound"
        case .omr: return "Omani Rial"
        case .qar: return "Qatari Riyal"
        case .sar: return "Saudi Riyal"
        case .syp: return "Syrian Pound"
        case .aed: return "UAE Dirham"
        case .yer: return "Yemeni Rial"
        case .bhd: return "Bahraini Dinar"
        case .bnd: return "Brunei Dollar"
        case .mop: return "Macanese Pataca"
        case .mvr: return "Maldivian Rufiyaa"
        case .zar: return "South African Rand"
        case .egp: return "Egyptian Pound"
        case .mad: return "Moroccan Dirham"
        case .tnd: return "Tunisian Dinar"
        case .lyd: return "Libyan Dinar"
        case .dzd: return "Algerian Dinar"
        case .ngn: return "Nigerian Naira"
        case .ghs: return "Ghanaian Cedi"
        case .kes: return "Kenyan Shilling"
        case .tzs: return "Tanzanian Shilling"
        case .ugx: return "Ugandan Shilling"
        case .etb: return "Ethiopian Birr"
        case .mzn: return "Mozambican Metical"
        case .zmw: return "Zambian Kwacha"
        case .mwk: return "Malawian Kwacha"
        case .rwf: return "Rwandan Franc"
        case .bif: return "Burundian Franc"
        case .cdf: return "Congolese Franc"
        case .djf: return "Djiboutian Franc"
        case .kmf: return "Comorian Franc"
        case .xof: return "CFA Franc BCEAO"
        case .xaf: return "CFA Franc BEAC"
        case .ern: return "Eritrean Nakfa"
        case .szl: return "Eswatini Lilangeni"
        case .lsl: return "Lesotho Loti"
        case .nad: return "Namibian Dollar"
        case .mur: return "Mauritian Rupee"
        case .scr: return "Seychellois Rupee"
        case .mga: return "Malagasy Ariary"
        case .gmd: return "Gambian Dalasi"
        case .gnf: return "Guinean Franc"
        case .lrd: return "Liberian Dollar"
        case .sle: return "Sierra Leonean Leone"
        case .sos: return "Somali Shilling"
        case .ssp: return "South Sudanese Pound"
        case .sdg: return "Sudanese Pound"
        case .stn: return "Sao Tome Dobra"
        case .cve: return "Cape Verdean Escudo"
        case .aoa: return "Angolan Kwanza"
        case .zwl: return "Zimbabwean Dollar"
        case .mru: return "Mauritanian Ouguiya"
        case .brl: return "Brazilian Real"
        case .mxn: return "Mexican Peso"
        case .ars: return "Argentine Peso"
        case .clp: return "Chilean Peso"
        case .cop: return "Colombian Peso"
        case .pen: return "Peruvian Sol"
        case .uyu: return "Uruguayan Peso"
        case .pyg: return "Paraguayan Guarani"
        case .bob: return "Boliviano"
        case .crc: return "Costa Rican Colon"
        case .gtq: return "Guatemalan Quetzal"
        case .hnl: return "Honduran Lempira"
        case .nio: return "Nicaraguan Cordoba"
        case .pab: return "Panamanian Balboa"
        case .dop: return "Dominican Peso"
        case .htg: return "Haitian Gourde"
        case .jmd: return "Jamaican Dollar"
        case .ttd: return "Trinidad & Tobago Dollar"
        case .bsd: return "Bahamian Dollar"
        case .bbd: return "Barbadian Dollar"
        case .bzd: return "Belize Dollar"
        case .gyd: return "Guyanese Dollar"
        case .srd: return "Surinamese Dollar"
        case .xcd: return "East Caribbean Dollar"
        case .fkp: return "Falkland Islands Pound"
        case .cuc: return "Cuban Convertible Peso"
        case .cup: return "Cuban Peso"
        case .ves: return "Venezuelan Bolivar"
        case .fjd: return "Fijian Dollar"
        case .pgk: return "Papua New Guinean Kina"
        case .wst: return "Samoan Tala"
        case .sbd: return "Solomon Islands Dollar"
        case .top: return "Tongan Paanga"
        case .vuv: return "Vanuatu Vatu"
        case .xpf: return "CFP Franc"
        }
    }
}
